export const PRACTICE_PROMPTS = [
  "Write as if you are speaking to your 13-year-old self. What would you say about why you are choosing UofT Engineering, and what parts of you you hope it will grow?",
  "Write a short letter to your younger self about the first time you felt proud of building or fixing something. How does that moment connect to your interest in UofT Engineering today?",
  "Write to your younger self who is worried about being not technical enough. What experiences changed your perspective, and how will UofT Engineering help you keep learning?",
  "Imagine your younger self asks, Why engineering? Answer them with a story from your life and explain how UofT Engineering fits into that story.",
  "Write as if you are narrating your journey from curiosity to commitment. What sparked your interest in engineering, and why does UofT feel like the right next step?",
  "Write a message to your younger self titled Keep going. What obstacles did you face in STEM or problem-solving, and how will you approach them at UofT Engineering?",
  "Write a reflection that begins with, I used to think engineers were..., but now I think... What changed, and how does UofT Engineering match your new understanding?",
  "Write to your younger self about a passion outside school (music, sports, art, community work). How do you see that passion intersecting with engineering at UofT?",
  "Imagine you are reading this after your first semester at UofT Engineering. What do you hope your younger self recognizes about your growth?",
  "Write a short dialogue between Past You and Present You about taking on challenging problems. What do you want UofT Engineering to teach you beyond technical skills?",

  "Describe a personal project (technical or non-technical) that you're proud of. What did it reveal about how you learn, and how would UofT Engineering help you push it further?",
  "What is a passion you want to turn into impact? Explain how you could use engineering at UofT to deepen that passion and apply it to real problems.",
  "Describe something you made, improved, or organized. What constraints did you face, and how would an engineering education at UofT change your next iteration?",
  "Pick one activity that energizes you (club, job, volunteering, hobby). Explain what it taught you that would make you a better engineering student at UofT.",
  "Describe a time you noticed a problem and couldn't stop thinking about it. What first steps did you take, and how would UofT Engineering help you continue?",
  "If you had 100 hours and access to UofT Engineering resources, what would you build or research? Why does it matter to you?",
  "Describe a topic you taught yourself (coding, electronics, design, writing, etc.). What kept you motivated, and how would UofT Engineering support your self-driven learning?",
  "Write about a time you combined two interests (for example, art and math, sports and data, environment and chemistry). How could UofT Engineering help you keep combining them?",
  "Describe the most meaningful feedback you've received on a project. How did you respond, and what would you want to improve at UofT Engineering?",
  "Choose one skill you want to master in university (design, communication, prototyping, analysis). Why that skill, and why UofT Engineering for it?",

  "Describe a situation where you had to solve a problem with limited time or resources. What did you prioritize, and what would you do differently with the tools of UofT Engineering?",
  "Explain a time you found a bug or mistake (in code, a plan, a model, or an argument). How did you debug it, and what did you learn about your thinking?",
  "Describe a system in your daily life that frustrates you (a school process, transit, scheduling, etc.). Propose an engineering-minded improvement and the tradeoffs you'd consider.",
  "When you face a complex problem, how do you break it down? Give a real example and connect it to how you expect to work at UofT Engineering.",
  "Describe a time you used data or evidence to make a decision. What did you measure, and how did you handle uncertainty?",
  "Think of a product or tool you use often. What is one design change that would improve it, and how would you test whether your change worked?",
  "Describe a time you had to communicate a technical or complex idea to someone else. What approach worked, and what would you improve?",
  "Write about a time you had to choose between a simple solution and a better-but-harder one. What choice did you make, and why?",
  "Describe a time you iterated: you tried, failed, adjusted, and tried again. What did iteration teach you that you want to bring to UofT Engineering?",
  "If you could attend one lecture or lab at UofT Engineering tomorrow, what topic would you pick and what question would you ask?",

  "Describe an issue in your community that you care about. How could engineering at UofT help you understand it and create responsible solutions?",
  "Write about a time you noticed an unfairness or barrier (accessibility, cost, language, bias). What would an ethical response look like, and how can engineers contribute?",
  "Describe a situation where convenience conflicted with doing the right thing. What did you do, and how does that experience shape the kind of engineer you want to be?",
  "Technology can help or harm. Choose one example from your life and explain what responsible engineering would mean in that context.",
  "Describe a time you had to consider others' perspectives when making a decision. How will you bring that perspective-taking to UofT Engineering teams?",
  "Write about a time you advocated for someone else or a better process. What did you learn about leadership and accountability?",
  "If you could use engineering to improve one aspect of student life or public life in Toronto, what would you focus on and why?",
  "Describe an ethical dilemma related to data, privacy, or AI. What principles would guide your decisions as a future engineer?",
  "Write about a time you had to admit you were wrong. Why was it hard, and how did it change your approach to working with others?",
  "What does impact mean to you? Define it using a concrete example and connect it to why you want to study engineering at UofT.",

  "Describe a concept that once felt impossible for you to learn. How did you eventually understand it, and what did that teach you about persistence?",
  "Write about a time you sought help (teacher, friend, online community). What did you learn about learning, and how will you use supports at UofT Engineering?",
  "Describe your approach to studying when you are overwhelmed. What strategy works best for you and why?",
  "Tell a story about a time you changed your approach after feedback. What did you change, and what improved?",
  "Describe a time you learned something quickly to meet a goal. What steps did you take, and how will you handle fast-paced learning at UofT Engineering?",
  "Write about a moment when your curiosity led you down a rabbit hole. What did you discover, and what does that say about how you learn?",
  "Describe a time you balanced depth versus breadth (going deep on one thing versus trying many). How do you decide, and how might that apply at UofT Engineering?",
  "What is a misconception you had about engineering or university? How did you revise it, and what are you excited to learn next?",
  "Write about a time you practiced a skill consistently over weeks or months. What kept you consistent, and how will you build habits at UofT?",
  "Describe a time you were challenged by ambiguity. How did you move forward without certainty, and what did you learn?",

  "Describe a team experience that taught you something important about collaboration. What role did you play, and what would you do differently now?",
  "Write about a time you led without a title. How did you influence the group, and what would you bring to UofT Engineering teams?",
  "Describe a time you had conflict with a teammate. How did you handle it, and what did you learn about communication?",
  "Tell a story about a time you supported someone else’s success. Why did it matter to you, and what did you learn?",
  "When you join a new team, how do you build trust? Give an example and connect it to how you’ll work in UofT Engineering.",
  "Describe a time you had to coordinate many moving parts (event, group project, family responsibility). How did you keep things on track?",
  "Write about a time your team was stuck. How did you help the group regain momentum?",
  "Describe a time you had to persuade others using evidence or reasoning. What approach worked best?",
  "Tell a story about a time you made room for quieter voices or different perspectives. What changed because of it?",
  "Imagine you are in a UofT Engineering design team where opinions differ. How would you help the team decide and move forward?",

  "Describe a setback that challenged your confidence. What did you do next, and how did you rebuild?",
  "Write about a time something you built or planned didn’t work. How did you respond, and what did you learn about iteration?",
  "Tell a story about a time you made a mistake that affected others. How did you take responsibility and repair the situation?",
  "Describe a time you had to continue performing under stress. What helped you stay grounded?",
  "Write about a time you failed at something you cared about. What did you take from that experience that will help you at UofT Engineering?",
  "Describe a time you faced criticism. What did you accept, what did you question, and what did you change?",
  "Tell a story about a time you had to start over. What did starting over teach you?",
  "Describe a time you had to make a hard tradeoff (time, energy, priorities). What did you choose and why?",
  "Write about a time you showed resilience in a non-academic part of your life. How does that resilience show up in how you learn?",
  "When you are stuck, what do you do first? Describe a real moment of being stuck and how you moved forward.",

  "What question do you keep asking about the world? Explain why it matters to you and how UofT Engineering could help you explore it.",
  "Describe a time you followed your curiosity beyond what was required. What did you learn, and what did it change for you?",
  "Write about a piece of technology you admire. What design choices stand out, and what would you want to learn to build something like it?",
  "Describe a science or engineering topic that fascinates you even when it’s hard. Why does it hold your attention?",
  "Tell a story about a time you tested an idea (experiment, prototype, survey). What did the result teach you?",
  "What does thinking like an engineer mean to you? Use an example from your life to explain.",
  "Describe a time you made a prediction and were surprised by the outcome. How did you respond to being surprised?",
  "If you could shadow an engineer for a day, what kind of engineer would you choose and what would you hope to learn?",
  "Write about a time you saw a pattern or connection others missed. What helped you notice it?",
  "Describe a time you used creativity to solve a problem. What made your approach creative?",

  "What values do you want to carry into engineering? Explain where those values come from and how you will live them at UofT.",
  "Write about a part of your identity or background that shapes how you solve problems. How does it influence your perspective?",
  "Describe a time you stepped outside your comfort zone. What did you learn about yourself as a learner?",
  "Write about a moment you felt a strong sense of purpose. What created that feeling, and how do you want to pursue purpose at UofT Engineering?",
  "Describe a time you noticed you were improving at something. What evidence convinced you you were growing?",
  "Tell a story about a time you helped build community (in a club, class, workplace, or online). What did you contribute?",
  "Write about a time you took initiative. What motivated you, and what did you learn about leading yourself?",
  "Describe a belief you hold strongly about education, technology, or responsibility. How did you form it?",
  "What does success look like for you in your first year at UofT Engineering? Be specific and explain why those goals matter.",
  "Write about a time you chose the harder path because it aligned with your goals or values. What happened?",

  "Why UofT Engineering specifically? Identify two things you hope to experience there (people, learning style, opportunities) and explain why they matter to you.",
  "Describe a community you want to be part of at UofT Engineering. What would you contribute and what would you hope to learn from others?",
  "Imagine you are giving advice to a friend applying to UofT Engineering. What would you tell them to focus on and why?",
  "Describe the kind of engineering problems you want to work on in Toronto or Canada. How could UofT help you prepare?",
  "If you had to pick one theme for your time at UofT Engineering (sustainability, accessibility, health, creativity, etc.), what would it be and why?",
  "Write about a time you worked across disciplines (for example, science and art, coding and writing). How would you continue that at UofT Engineering?",
  "Describe how you want to grow in communication during your degree. Why is communication important for engineers?",
  "Imagine a UofT Engineering group project where the goal is unclear. How would you help define the problem before building solutions?",
  "Write about what you hope your classmates will say about you after a tough team project at UofT Engineering.",
  "Write a short closing paragraph that could end your application: what excites you most about becoming an engineer at UofT, and what do you want to give back?",
] as const;

export function getRandomPrompt(): string {
  return PRACTICE_PROMPTS[Math.floor(Math.random() * PRACTICE_PROMPTS.length)]!;
}

export const VIDEO_INTERVIEW_PROMPTS = [
  "What is a topic you learned in school that interested you in engineering? Have you pursued this outside of school?",
  "Think of how engineers made an impact on a community or environment you care about. Explain it and why you think it's meaningful. Where and when did you find out about this? How did this impact your view of engineers? If you've done any similar work in a field, tell us about it.",
  "Let's say Person A has trouble scoring good grades. Person B recommends they just review harder, C suggests using other classmates' notes, and D suggests getting tutoring. What is your opinion on this?",
  "Describe an experience that helped you learn something important. What did you take away from it?",
  "Describe a project (school, club, work, or personal) that made you feel like an engineer. What was your role and what did you learn?",
  "Tell us about a time you were curious about how something worked and decided to investigate. What did you do and what did you discover?",
  "Describe a time you had to learn a new skill quickly. How did you approach it and what was the outcome?",
  "Tell a story about a time you failed at something you cared about. What did you change afterward?",
  "Describe a time you received critical feedback. What did you agree with, what did you disagree with, and how did you respond?",
  "Tell us about a time you helped someone else understand a concept. How did you explain it and why did your approach work?",
  "Describe a situation where you had to make a decision with incomplete information. What did you prioritize and why?",
  "Tell us about a time you noticed a problem in your community or school. What first steps did you take to address it?",
  "Describe a time you improved something (a process, a product, or a routine). What was the change and how did you measure success?",
  "Tell us about a time you worked on a team with different opinions. How did you help the team move forward?",
  "Describe a time you took initiative without being asked. What motivated you and what happened?",
  "Tell us about a time you were overwhelmed by a challenge. What helped you stay grounded and keep going?",
  "Describe a time you balanced multiple responsibilities. How did you organize your time and make tradeoffs?",
  "Tell us about a time you changed your mind after learning new information. What changed and why?",
  "Describe a time you made a mistake that affected others. How did you take responsibility and repair it?",
  "Tell us about a time you had to advocate for yourself or someone else. What did you do and what did you learn?",
  "Describe a time you had to communicate under pressure (presentation, competition, interview, or conflict). What did you do well and what would you improve?",
  "Tell us about a time you worked with someone who was struggling. How did you support them while still meeting your goals?",
  "Describe a time you had to persuade someone using evidence or reasoning. What did you say and what was the result?",
  "Tell us about a time you led by listening. What did you learn from others and how did it change your plan?",
  "Describe a moment when you felt proud of your growth as a learner. What convinced you that you were improving?",
  "Tell us about a time you tried something new outside of school (club, job, volunteering, self-study). What did it teach you?",
  "Describe a time you turned a vague task into a clear plan. What questions did you ask and what steps did you take?",
  "Tell us about a time you had to work with limited resources (time, money, tools, or information). How did you adapt?",
  "Describe an experience that shaped your interest in engineering at UofT specifically. What stands out to you about the program or community?",
  "Tell us about a technology you use often. What is one improvement you would make and how would you test it?",
  "Describe a time you used data (even informal data) to make a decision. What did you measure and what did it change?",
  "Tell us about a time you built something for someone else (a tool, a plan, a resource, a solution). What did you learn from their needs?",
  "Describe a time you worked across differences (backgrounds, skills, or perspectives). What did you do to build trust?",
  "Tell us about a time you handled conflict respectfully. What did you say and what was the outcome?",
  "Describe a time you had to keep going after disappointment. What did you do in the next 24 hours and the next week?",
  "Tell us about a time you identified a root cause instead of treating symptoms. How did you figure it out?",
  "Describe a time you improved your communication (writing, speaking, or listening). What practice helped the most?",
  "Tell us about a moment when you had to choose between a faster solution and a better solution. What did you choose and why?",
  "Describe a time you made space for quieter voices or different perspectives. What changed because of it?",
  "Tell us about a time you collaborated with someone more experienced than you. How did you learn from them?",
  "Describe a time you collaborated with someone less experienced than you. How did you help them grow?",
  "Tell us about a time you had to handle a setback in a group project. What did you do to regain momentum?",
  "Describe an example of responsible decision-making. What values guided your choice?",
  "Audio question: A teammate is not contributing much. Some people want to remove them, others want to redistribute tasks quietly, and others want to talk directly. What would you do and why?",
  "Audio question: Someone shares an idea in a group, and later another person repeats it and gets the credit. What would you do in the moment and afterward?",
  "Audio question: Your friend asks to copy your homework because they are stressed. What would you say and why?",
  "Audio question: A club you are in has a limited budget. Some want to spend it on better equipment, others want to run outreach events. How would you decide?",
  "Audio question: You notice a safety issue during a lab activity or workshop. What steps would you take and why?",
  "Tell us about a time you asked for help. How did you ask, and what did you learn about yourself from that experience?",
  "Describe a long-term goal you worked toward. What kept you consistent, and what did you do when motivation dropped?",
] as const;

export const THREE_VARIABLE_VIDEO_PROMPTS = [
  "You're a member of the solar panel vehicle team at UofT and you're tasked with transporting the vehicle from Australia to Vienna. What are the three most important variables you would need to ensure the vehicle arrives safely and on time? How would these three variables help you form your logistics plan?",
  "There's a popular store that UofT students and staff enjoy, but it's really crowded due to its popularity. What are three variables you would consider to improve customer flow and reduce crowdedness, and why?",
  "You're a league bowler and have 6 different bowling balls of different weights. You have a stopwatch and a tape measure. If you were to conduct an experiment, what are the three most important variables you would track, and why?",
  "You're coordinating a team project with a hard deadline and multiple dependencies. What three variables would you track daily to keep the project on time, and why?",
  "You are designing a study schedule for a heavy week of tests and assignments. What three variables would you consider to make the schedule realistic and effective, and why?",
  "A UofT engineering club is hosting a workshop with limited seats. What three variables should you consider to maximize learning and fairness for attendees, and why?",
  "You're setting up an experiment to see which paper airplane design flies farthest. What three variables would you control or measure, and why?",
  "You're testing which battery brand lasts longest in a small device. What three variables would you track to make the comparison fair, and why?",
  "You're improving the flow of a crowded school cafeteria line. What three variables would you measure first, and how would they guide your changes?",
  "You're planning a charity event fundraiser. What three variables would you focus on to maximize funds raised, and why?",
  "You're organizing transportation for a team traveling to a competition. What three variables matter most to keep costs low and arrival reliable, and why?",
  "You're building a simple bridge out of popsicle sticks. What three variables would you prioritize to maximize strength, and why?",
  "You're designing a water filtration demo for younger students. What three variables would you consider to make it safe, clear, and effective, and why?",
  "You're optimizing a smartphone app feature to reduce loading time. What three variables would you measure, and why?",
  "You're trying to reduce energy use in your home for a month. What three variables would you track, and how would they shape your plan?",
  "You're setting up a robot to follow a line reliably. What three variables would you tune or measure, and why?",
  "You're designing a bike route plan for commuting to campus. What three variables would you consider to choose the best route, and why?",
  "You're running an experiment to see which type of shoe sole has the most grip on wet tile. What three variables would you control or measure, and why?",
  "You're planning a study to compare two note-taking methods. What three variables would you track to decide which works better, and why?",
  "You're coordinating a group presentation where one member is remote. What three variables would you manage to ensure a smooth presentation, and why?",
  "You're designing a backpack to be more ergonomic. What three variables would you consider to evaluate comfort and safety, and why?",
  "You're improving the flow of pedestrians through a busy hallway between classes. What three variables would you focus on, and why?",
  "You're setting up a small greenhouse experiment to grow plants faster. What three variables would you control or measure, and why?",
  "You're comparing two different coding approaches to solve the same problem. What three variables would you use to evaluate them, and why?",
  "You're planning how to ship fragile lab equipment to a conference. What three variables matter most to prevent damage and delays, and why?",
  "You're designing a system to reduce food waste in a school cafeteria. What three variables would you track first, and why?",
  "You're tasked with improving Wi‑Fi reliability in a busy student space. What three variables would you investigate first, and why?",
  "You're running a tutoring program and want to improve outcomes. What three variables would you track to see if it's working, and why?",
  "You're testing how different ramp angles affect a rolling cart's speed. What three variables would you measure or control, and why?",
  "You're planning a volunteer schedule for a community event. What three variables matter most to keep coverage consistent, and why?",
  "You're evaluating two different materials for a phone case. What three variables would you use to compare them, and why?",
  "You're planning a campus orientation route for new students. What three variables would you consider to make it safe and smooth, and why?",
  "You're designing an experiment to see which type of music helps you focus best. What three variables would you control or measure, and why?",
  "You're asked to reduce waiting time at a popular campus service desk. What three variables would you use to diagnose the bottleneck, and why?",
  "You're planning an outreach trip with limited time at each school. What three variables would shape your itinerary, and why?",
  "You're improving the safety of a busy crosswalk near campus. What three variables would you analyze first, and why?",
  "You're testing which insulation keeps a cup of hot water warm longest. What three variables would you track, and why?",
  "You're preparing a logistics plan for moving a large exhibit into a building. What three variables would you prioritize, and why?",
  "You're designing a fitness routine and want to track progress. What three variables would you track to know it's working, and why?",
  "You're comparing two different study resources for learning calculus. What three variables would you use to decide which is better for you, and why?",
  "You're planning a social media campaign for a club event. What three variables would you track to see if it's effective, and why?",
  "You're choosing between two part-time jobs. What three variables would you consider to make the best decision, and why?",
  "You're designing a small prototype that must fit in a tiny box. What three variables would guide your design constraints, and why?",
  "You're testing how different types of wheels affect a small car's travel distance. What three variables would you track, and why?",
  "You're improving audio quality for an online meeting room. What three variables would you adjust or measure, and why?",
  "You're planning a budget for your first year at university. What three variables would you track to avoid running out of money, and why?",
  "You're organizing a hackathon schedule. What three variables would you manage to maximize productivity and participant experience, and why?",
  "You're designing a system to keep a laptop from overheating. What three variables would you focus on, and why?",
  "You're tasked with improving recycling rates in a dorm or school. What three variables would you track to understand behavior and improve outcomes, and why?",
  "You're planning how to test a new study app feature with students. What three variables would you measure to decide if it's successful, and why?",
] as const;

export function getRandomVideoInterviewPrompt(): string {
  return VIDEO_INTERVIEW_PROMPTS[
    Math.floor(Math.random() * VIDEO_INTERVIEW_PROMPTS.length)
  ]!;
}

export function getRandomThreeVariableVideoPrompt(): string {
  return THREE_VARIABLE_VIDEO_PROMPTS[
    Math.floor(Math.random() * THREE_VARIABLE_VIDEO_PROMPTS.length)
  ]!;
}
