export const PRACTICE_PROMPTS = [
  "Write as if you are speaking to your 13-year-old self. What would you say about why you are choosing UofT Engineering, and what parts of you you hope it will grow?",
  "Write a short letter to your younger self about the first time you felt proud of building or fixing something. How does that moment connect to your interest in UofT Engineering today?",
  "Write to your younger self who is worried about being not technical enough. What experiences changed your perspective, and how will UofT Engineering help you keep learning?",
  "Imagine your younger self asks, Why engineering? Answer them with a story from your life and explain how UofT Engineering fits into that story.",
  "Write as if you are narrating your journey from curiosity to commitment. What sparked your interest in engineering, and why does UofT feel like the right next step?",
  "Write a message to your younger self titled Keep going. What obstacles did you face in STEM or problem-solving, and how will you approach them at UofT Engineering?",
  "Write a reflection that begins with, I used to think engineers were..., but now I think... What changed, and how does UofT Engineering match your new understanding?",
  "Write to your younger self about a passion outside school (music, sports, art, community work). How do you see that passion intersecting with engineering at UofT?",
  "Imagine you are reading this after your first semester at UofT Engineering. What do you hope your younger self recognizes about your growth?",
  "Write a short dialogue between Past You and Present You about taking on challenging problems. What do you want UofT Engineering to teach you beyond technical skills?",

  "Describe a personal project (technical or non-technical) that you're proud of. What did it reveal about how you learn, and how would UofT Engineering help you push it further?",
  "What is a passion you want to turn into impact? Explain how you could use engineering at UofT to deepen that passion and apply it to real problems.",
  "Describe something you made, improved, or organized. What constraints did you face, and how would an engineering education at UofT change your next iteration?",
  "Pick one activity that energizes you (club, job, volunteering, hobby). Explain what it taught you that would make you a better engineering student at UofT.",
  "Describe a time you noticed a problem and couldn't stop thinking about it. What first steps did you take, and how would UofT Engineering help you continue?",
  "If you had 100 hours and access to UofT Engineering resources, what would you build or research? Why does it matter to you?",
  "Describe a topic you taught yourself (coding, electronics, design, writing, etc.). What kept you motivated, and how would UofT Engineering support your self-driven learning?",
  "Write about a time you combined two interests (for example, art and math, sports and data, environment and chemistry). How could UofT Engineering help you keep combining them?",
  "Describe the most meaningful feedback you've received on a project. How did you respond, and what would you want to improve at UofT Engineering?",
  "Choose one skill you want to master in university (design, communication, prototyping, analysis). Why that skill, and why UofT Engineering for it?",

  "Describe a situation where you had to solve a problem with limited time or resources. What did you prioritize, and what would you do differently with the tools of UofT Engineering?",
  "Explain a time you found a bug or mistake (in code, a plan, a model, or an argument). How did you debug it, and what did you learn about your thinking?",
  "Describe a system in your daily life that frustrates you (a school process, transit, scheduling, etc.). Propose an engineering-minded improvement and the tradeoffs you'd consider.",
  "When you face a complex problem, how do you break it down? Give a real example and connect it to how you expect to work at UofT Engineering.",
  "Describe a time you used data or evidence to make a decision. What did you measure, and how did you handle uncertainty?",
  "Think of a product or tool you use often. What is one design change that would improve it, and how would you test whether your change worked?",
  "Describe a time you had to communicate a technical or complex idea to someone else. What approach worked, and what would you improve?",
  "Write about a time you had to choose between a simple solution and a better-but-harder one. What choice did you make, and why?",
  "Describe a time you iterated: you tried, failed, adjusted, and tried again. What did iteration teach you that you want to bring to UofT Engineering?",
  "If you could attend one lecture or lab at UofT Engineering tomorrow, what topic would you pick and what question would you ask?",

  "Describe an issue in your community that you care about. How could engineering at UofT help you understand it and create responsible solutions?",
  "Write about a time you noticed an unfairness or barrier (accessibility, cost, language, bias). What would an ethical response look like, and how can engineers contribute?",
  "Describe a situation where convenience conflicted with doing the right thing. What did you do, and how does that experience shape the kind of engineer you want to be?",
  "Technology can help or harm. Choose one example from your life and explain what responsible engineering would mean in that context.",
  "Describe a time you had to consider others' perspectives when making a decision. How will you bring that perspective-taking to UofT Engineering teams?",
  "Write about a time you advocated for someone else or a better process. What did you learn about leadership and accountability?",
  "If you could use engineering to improve one aspect of student life or public life in Toronto, what would you focus on and why?",
  "Describe an ethical dilemma related to data, privacy, or AI. What principles would guide your decisions as a future engineer?",
  "Write about a time you had to admit you were wrong. Why was it hard, and how did it change your approach to working with others?",
  "What does impact mean to you? Define it using a concrete example and connect it to why you want to study engineering at UofT.",

  "Describe a concept that once felt impossible for you to learn. How did you eventually understand it, and what did that teach you about persistence?",
  "Write about a time you sought help (teacher, friend, online community). What did you learn about learning, and how will you use supports at UofT Engineering?",
  "Describe your approach to studying when you are overwhelmed. What strategy works best for you and why?",
  "Tell a story about a time you changed your approach after feedback. What did you change, and what improved?",
  "Describe a time you learned something quickly to meet a goal. What steps did you take, and how will you handle fast-paced learning at UofT Engineering?",
  "Write about a moment when your curiosity led you down a rabbit hole. What did you discover, and what does that say about how you learn?",
  "Describe a time you balanced depth versus breadth (going deep on one thing versus trying many). How do you decide, and how might that apply at UofT Engineering?",
  "What is a misconception you had about engineering or university? How did you revise it, and what are you excited to learn next?",
  "Write about a time you practiced a skill consistently over weeks or months. What kept you consistent, and how will you build habits at UofT?",
  "Describe a time you were challenged by ambiguity. How did you move forward without certainty, and what did you learn?",

  "Describe a team experience that taught you something important about collaboration. What role did you play, and what would you do differently now?",
  "Write about a time you led without a title. How did you influence the group, and what would you bring to UofT Engineering teams?",
  "Describe a time you had conflict with a teammate. How did you handle it, and what did you learn about communication?",
  "Tell a story about a time you supported someone else’s success. Why did it matter to you, and what did you learn?",
  "When you join a new team, how do you build trust? Give an example and connect it to how you’ll work in UofT Engineering.",
  "Describe a time you had to coordinate many moving parts (event, group project, family responsibility). How did you keep things on track?",
  "Write about a time your team was stuck. How did you help the group regain momentum?",
  "Describe a time you had to persuade others using evidence or reasoning. What approach worked best?",
  "Tell a story about a time you made room for quieter voices or different perspectives. What changed because of it?",
  "Imagine you are in a UofT Engineering design team where opinions differ. How would you help the team decide and move forward?",

  "Describe a setback that challenged your confidence. What did you do next, and how did you rebuild?",
  "Write about a time something you built or planned didn’t work. How did you respond, and what did you learn about iteration?",
  "Tell a story about a time you made a mistake that affected others. How did you take responsibility and repair the situation?",
  "Describe a time you had to continue performing under stress. What helped you stay grounded?",
  "Write about a time you failed at something you cared about. What did you take from that experience that will help you at UofT Engineering?",
  "Describe a time you faced criticism. What did you accept, what did you question, and what did you change?",
  "Tell a story about a time you had to start over. What did starting over teach you?",
  "Describe a time you had to make a hard tradeoff (time, energy, priorities). What did you choose and why?",
  "Write about a time you showed resilience in a non-academic part of your life. How does that resilience show up in how you learn?",
  "When you are stuck, what do you do first? Describe a real moment of being stuck and how you moved forward.",

  "What question do you keep asking about the world? Explain why it matters to you and how UofT Engineering could help you explore it.",
  "Describe a time you followed your curiosity beyond what was required. What did you learn, and what did it change for you?",
  "Write about a piece of technology you admire. What design choices stand out, and what would you want to learn to build something like it?",
  "Describe a science or engineering topic that fascinates you even when it’s hard. Why does it hold your attention?",
  "Tell a story about a time you tested an idea (experiment, prototype, survey). What did the result teach you?",
  "What does thinking like an engineer mean to you? Use an example from your life to explain.",
  "Describe a time you made a prediction and were surprised by the outcome. How did you respond to being surprised?",
  "If you could shadow an engineer for a day, what kind of engineer would you choose and what would you hope to learn?",
  "Write about a time you saw a pattern or connection others missed. What helped you notice it?",
  "Describe a time you used creativity to solve a problem. What made your approach creative?",

  "What values do you want to carry into engineering? Explain where those values come from and how you will live them at UofT.",
  "Write about a part of your identity or background that shapes how you solve problems. How does it influence your perspective?",
  "Describe a time you stepped outside your comfort zone. What did you learn about yourself as a learner?",
  "Write about a moment you felt a strong sense of purpose. What created that feeling, and how do you want to pursue purpose at UofT Engineering?",
  "Describe a time you noticed you were improving at something. What evidence convinced you you were growing?",
  "Tell a story about a time you helped build community (in a club, class, workplace, or online). What did you contribute?",
  "Write about a time you took initiative. What motivated you, and what did you learn about leading yourself?",
  "Describe a belief you hold strongly about education, technology, or responsibility. How did you form it?",
  "What does success look like for you in your first year at UofT Engineering? Be specific and explain why those goals matter.",
  "Write about a time you chose the harder path because it aligned with your goals or values. What happened?",

  "Why UofT Engineering specifically? Identify two things you hope to experience there (people, learning style, opportunities) and explain why they matter to you.",
  "Describe a community you want to be part of at UofT Engineering. What would you contribute and what would you hope to learn from others?",
  "Imagine you are giving advice to a friend applying to UofT Engineering. What would you tell them to focus on and why?",
  "Describe the kind of engineering problems you want to work on in Toronto or Canada. How could UofT help you prepare?",
  "If you had to pick one theme for your time at UofT Engineering (sustainability, accessibility, health, creativity, etc.), what would it be and why?",
  "Write about a time you worked across disciplines (for example, science and art, coding and writing). How would you continue that at UofT Engineering?",
  "Describe how you want to grow in communication during your degree. Why is communication important for engineers?",
  "Imagine a UofT Engineering group project where the goal is unclear. How would you help define the problem before building solutions?",
  "Write about what you hope your classmates will say about you after a tough team project at UofT Engineering.",
  "Write a short closing paragraph that could end your application: what excites you most about becoming an engineer at UofT, and what do you want to give back?",
] as const;

export function getRandomPrompt(): string {
  return PRACTICE_PROMPTS[Math.floor(Math.random() * PRACTICE_PROMPTS.length)]!;
}
